"""Declarative base, naming convention and reusable column groups ("mixins").

A mixin is a small class whose columns are copied into every table that inherits it,
so e.g. all data tables get the same five provenance columns.
"""

from __future__ import annotations

import uuid
from collections.abc import Iterable
from datetime import datetime

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    MetaData,
    String,
    Text,
    func,
    text,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column

# Size of skill embedding vectors. It must match the embedding model we choose
# (both candidates in docs/04-architecture.md §4.3 produce 384 numbers).
# Changing it later requires a migration.
EMBEDDING_DIM = 384

# Predictable constraint/index names, so Alembic migrations are stable and readable.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Parent class for every table."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
    # Every Python `datetime` column is stored WITH time zone (timestamptz).
    type_annotation_map = {datetime: DateTime(timezone=True)}


# --------------------------------------------------------------------------- mixins
class UUIDPrimaryKey:
    """`id` column: a random UUID, generated by Python or by PostgreSQL."""

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True, default=uuid.uuid4, server_default=func.gen_random_uuid()
    )


class CreatedAt:
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())


class Timestamps(CreatedAt):
    """`created_at` and `updated_at` (updated automatically when the ORM changes a row)."""

    updated_at: Mapped[datetime] = mapped_column(server_default=func.now(), onupdate=func.now())


class Provenance:
    """Where a record came from (docs/04-architecture.md §9.2).

    source        : source ID from docs/DATA_SOURCE_INVENTORY.md,
                    e.g. "S18" (real) or "Y01" (synthetic)
    source_ref    : where exactly in the source, e.g. "Electrician syllabus PDF, page 12"
    fetched_at    : when we downloaded / collected it
    license_note  : license or terms note, or "TODO-VERIFY"
    is_synthetic  : TRUE for generated demo data (shown with a "demo data" badge)
    """

    source: Mapped[str] = mapped_column(String(64))
    source_ref: Mapped[str | None] = mapped_column(Text)
    fetched_at: Mapped[datetime | None]
    license_note: Mapped[str | None] = mapped_column(Text)
    is_synthetic: Mapped[bool] = mapped_column(default=False, server_default=text("false"))

    @declared_attr
    def ingestion_run_id(cls) -> Mapped[uuid.UUID | None]:  # noqa: N805 (SQLAlchemy pattern)
        return mapped_column(ForeignKey("ingestion_run.id", ondelete="SET NULL"), index=True)


class OfficialCode:
    """A government/official identifier that must be verified before we trust it.

    We never invent official codes. Until verified, `official_code` may be NULL or hold a
    placeholder such as "TODO-VERIFY", and `official_code_verified` stays FALSE.
    `official_code_scheme` says which system the code belongs to (e.g. "LGD", "NCO-2015",
    "NQR", "DGT", "DVET").
    """

    official_code: Mapped[str | None] = mapped_column(String(64))
    official_code_scheme: Mapped[str | None] = mapped_column(String(32))
    official_code_verified: Mapped[bool] = mapped_column(
        default=False, server_default=text("false")
    )


# --------------------------------------------------------------------------- helpers
def check_in(name: str, column: str, allowed: Iterable[str]) -> CheckConstraint:
    """CHECK constraint: `column` must be one of the allowed values (NULL is allowed)."""
    values = ", ".join(f"'{value}'" for value in allowed)
    return CheckConstraint(f"{column} IN ({values})", name=name)


def between(name: str, column: str, low: float, high: float) -> CheckConstraint:
    """CHECK constraint: low <= column <= high (NULL is allowed)."""
    return CheckConstraint(f"{column} >= {low} AND {column} <= {high}", name=name)


def quarter_format(name: str, column: str) -> CheckConstraint:
    """CHECK constraint: text like '2026Q3'."""
    return CheckConstraint(f"{column} ~ '^[0-9]{{4}}Q[1-4]$'", name=name)


def academic_year_format(name: str, column: str) -> CheckConstraint:
    """CHECK constraint: text like '2025-26'."""
    return CheckConstraint(f"{column} ~ '^[0-9]{{4}}-[0-9]{{2}}$'", name=name)


def json_array(name: str, column: str) -> CheckConstraint:
    return CheckConstraint(f"jsonb_typeof({column}) = 'array'", name=name)


def json_object(name: str, column: str) -> CheckConstraint:
    return CheckConstraint(f"jsonb_typeof({column}) = 'object'", name=name)


def official_code_rules(table: str, *extra_unique_columns: str) -> tuple:
    """Rules for tables using OfficialCode:

    1. A code can only be marked verified if it is present and not a TODO placeholder.
    2. Verified codes must be unique (placeholders may repeat).
    """
    return (
        CheckConstraint(
            "NOT official_code_verified OR "
            "(official_code IS NOT NULL AND official_code NOT LIKE 'TODO%')",
            name="official_code_verified_requires_code",
        ),
        Index(
            f"uq_{table}_verified_official_code",
            "official_code_scheme",
            "official_code",
            *extra_unique_columns,
            unique=True,
            postgresql_where=text("official_code_verified"),
        ),
    )
