"""Write the synthetic dataset as CSV files + manifest.json, and read it back.

    write_export(dataset, directory, manifest_info)   # one <table>.csv per table
    dataset = read_export(directory, config)          # typed values again

CSV rules (so the files are identical on every machine and easy to open):
UTF-8 without BOM, "\n" line endings, a header row with the database column names,
empty cell = NULL, true/false for booleans, JSON text for lists and JSON columns.
Every synthetic row carries is_synthetic = true.

Sector and district rows are NOT exported: they come from config/*.yaml and are not
synthetic. read_export() rebuilds them from the configuration.
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
import os
import shutil
import uuid
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any

from sqlalchemy import Boolean, Date, DateTime, Float, Integer, Numeric, Uuid
from sqlalchemy.dialects.postgresql import ARRAY, JSONB

from app.config import ProductConfig
from app.models import Base
from app.synthetic.generator import GENERATOR_VERSION, Dataset, reference_rows
from app.synthetic.tables import SYNTHETIC_TABLES, columns

MANIFEST = "manifest.json"
SUMMARY = "summary.json"
DISCLAIMER = (
    "SYNTHETIC DEMO DATA. Generated by the KaushalSetu prototype from a hand-written spec "
    "and a fixed seed. Institutes, employers and people are fictional; all numbers are team "
    "assumptions that plant known patterns. Never present them as real or official statistics."
)


class ExportError(Exception):
    """The export folder is missing files, has changed files, or cannot be parsed."""


# --------------------------------------------------------------------------- encoding
def _to_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def encode(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (list, dict)):
        return _to_json(value)
    if isinstance(value, (datetime, date)):
        return value.isoformat()
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str) and value == "":
        raise ExportError("empty strings cannot be exported (an empty cell means NULL)")
    return str(value)


def decode(text: str, column_type: Any) -> Any:
    if text == "":
        return None
    if isinstance(column_type, Uuid):
        return uuid.UUID(text)
    if isinstance(column_type, Boolean):
        if text not in ("true", "false"):
            raise ExportError(f"not a boolean: {text!r}")
        return text == "true"
    if isinstance(column_type, (ARRAY, JSONB)):
        return json.loads(text)
    if isinstance(column_type, DateTime):
        return datetime.fromisoformat(text)
    if isinstance(column_type, Date):
        return date.fromisoformat(text)
    if isinstance(column_type, Float):
        return float(text)
    if isinstance(column_type, Numeric):
        return Decimal(text)
    if isinstance(column_type, Integer):
        return int(text)
    return text


def table_csv(table: str, rows: list[dict[str, Any]]) -> bytes:
    buffer = io.StringIO(newline="")
    writer = csv.writer(buffer, lineterminator="\n")
    header = columns(table)
    writer.writerow(header)
    for row in rows:
        writer.writerow([encode(row[column]) for column in header])
    return buffer.getvalue().encode("utf-8")


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def file_sha256(path: Path) -> str:
    """Hash that is the same on Windows (CRLF checkout) and Linux (LF)."""
    return _sha256(path.read_bytes().replace(b"\r\n", b"\n"))


# --------------------------------------------------------------------------- write
def write_export(
    dataset: Dataset,
    directory: Path,
    config: ProductConfig,
    *,
    seed: int,
    spec_file: str,
    spec_sha256: str,
    generated_at: datetime,
    as_of: date,
    summary: dict[str, Any] | None = None,
) -> list[Path]:
    """Write <table>.csv for every synthetic table, manifest.json and (optionally)
    summary.json.

    Safety: a non-empty folder without manifest.json is refused (it is not an export), and
    only files listed in the previous manifest are ever removed. Files are written to a
    staging folder first and then moved into place, manifest last; if a move fails (e.g. a
    CSV is open in Excel) the old manifest no longer matches, so the half-written export is
    refused when read. OSError is raised to the caller."""
    directory = directory.resolve()
    previous: set[str] = set()
    if directory.exists() and any(directory.iterdir()):
        if not (directory / MANIFEST).is_file():
            raise ExportError(
                f"{directory} is not empty and has no {MANIFEST}, so it is not an export "
                "folder. Choose an empty or new folder."
            )
        try:
            previous = {entry["file"] for entry in read_manifest(directory)["files"]}
            previous.add(SUMMARY)
        except ExportError:
            previous = set()

    contents: dict[str, bytes] = {}
    files = []
    source_ids = config.synthetic.source_ids
    for info in SYNTHETIC_TABLES:
        data = table_csv(info.name, dataset[info.name])
        name = f"{info.name}.csv"
        contents[name] = data
        files.append(
            {
                "table": info.name,
                "file": name,
                "source": getattr(source_ids, info.dataset),
                "rows": len(dataset[info.name]),
                "sha256": _sha256(data),
            }
        )
    history = config.synthetic.history
    manifest = {
        "dataset": "KaushalSetu synthetic demo world",
        "is_synthetic": True,
        "disclaimer": DISCLAIMER,
        "generator_version": GENERATOR_VERSION,
        "seed": seed,
        "spec_file": spec_file,
        "spec_sha256": spec_sha256,
        "generated_at": generated_at.isoformat(),
        "as_of": as_of.isoformat(),
        "history": {"start_quarter": history.start_quarter, "end_quarter": history.end_quarter},
        "planted_patterns": {
            key: pattern.description
            for key, pattern in config.synthetic.planted_patterns.items()
            if pattern.enabled
        },
        "reference_tables": "sector and district rows come from config/sectors.yaml and "
        "config/scope.yaml (not synthetic, not exported)",
        "files": files,
    }
    if summary is not None:
        contents[SUMMARY] = _json_bytes(summary)
    contents[MANIFEST] = _json_bytes(manifest)  # last: it vouches for the files above

    staging = directory.parent / f".{directory.name}.staging"
    shutil.rmtree(staging, ignore_errors=True)
    staging.mkdir(parents=True)
    for name, data in contents.items():
        (staging / name).write_bytes(data)
    directory.mkdir(parents=True, exist_ok=True)
    for name in contents:
        os.replace(staging / name, directory / name)
    staging.rmdir()
    for stale in previous - set(contents):
        (directory / stale).unlink(missing_ok=True)
    return [directory / name for name in contents]


def _json_bytes(content: dict[str, Any]) -> bytes:
    return (json.dumps(content, ensure_ascii=False, indent=2) + "\n").encode("utf-8")


def spec_digest(spec_path: Path) -> str:
    """Hash of the spec file that is the same on Windows (CRLF) and Linux (LF)."""
    return _sha256(spec_path.read_bytes().replace(b"\r\n", b"\n"))


def staleness(manifest: dict[str, Any], spec_path: Path) -> list[str]:
    """Why an export no longer matches the current spec file or generator ([] = up to date)."""
    problems = []
    if manifest.get("spec_sha256") != spec_digest(spec_path):
        problems.append("the world spec changed after this export was generated")
    if manifest.get("generator_version") != GENERATOR_VERSION:
        problems.append(
            f"it was made by generator v{manifest.get('generator_version')}; the current "
            f"generator is v{GENERATOR_VERSION}"
        )
    return problems


# --------------------------------------------------------------------------- read
def read_manifest(directory: Path) -> dict[str, Any]:
    path = directory / MANIFEST
    if not path.is_file():
        raise ExportError(
            f"No {MANIFEST} in {directory}. Generate the export first: "
            "python -m app.cli.synthetic generate"
        )
    try:
        manifest = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        raise ExportError(
            f"{path} is damaged ({exc}). Regenerate: python -m app.cli.synthetic generate"
        ) from None
    files = manifest.get("files") if isinstance(manifest, dict) else None
    if not isinstance(files, list) or not all(
        isinstance(f, dict) and {"table", "file", "rows", "sha256"} <= set(f) for f in files
    ):
        raise ExportError(f"{path} has no valid 'files' list. Regenerate the export.")
    return manifest


def read_export(directory: Path, config: ProductConfig) -> tuple[Dataset, dict[str, Any]]:
    """Read and type-check every CSV listed in the manifest. The file hashes must match
    the manifest (so hand-edited or half-written exports are refused)."""
    manifest = read_manifest(directory)
    listed = {entry["table"]: entry for entry in manifest["files"]}
    dataset: Dataset = dict(reference_rows(config))
    for info in SYNTHETIC_TABLES:
        entry = listed.get(info.name)
        if entry is None:
            raise ExportError(f"{MANIFEST} does not list the {info.name} table")
        path = directory / entry["file"]
        if not path.is_file():
            raise ExportError(f"Missing export file: {path}")
        if file_sha256(path) != entry["sha256"]:
            raise ExportError(
                f"{path.name} does not match {MANIFEST} (edited by hand?). Regenerate: "
                "python -m app.cli.synthetic generate"
            )
        table = Base.metadata.tables[info.name]
        with path.open(encoding="utf-8", newline="") as handle:
            reader = csv.reader(handle)
            header = next(reader, None)
            if header != columns(info.name):
                raise ExportError(f"{path.name}: unexpected columns {header}")
            rows = []
            for line, record in enumerate(reader, start=2):
                try:
                    rows.append(
                        {
                            name: decode(cell, table.c[name].type)
                            for name, cell in zip(header, record, strict=True)
                        }
                    )
                except (ValueError, KeyError) as exc:
                    raise ExportError(
                        f"{path.name} line {line}: cannot read a value ({exc})"
                    ) from None
        if len(rows) != entry["rows"]:
            raise ExportError(f"{path.name}: {len(rows)} rows, manifest says {entry['rows']}")
        dataset[info.name] = rows
    return dataset, manifest
